### ISSUE TITLE
Unable to report a YouTube channel.

### ISSUE THREAD

**Issue by Ben-Fenner** [own3mall/YouTubeNonStop-Legacy-XUL-Extension#1]
Today I was unable to report a channel for impersonation/scam content while this extension is active.

Steps to reproduce:
Visit any YouTube channel's "About" page.
Find the flag icon toward the bottom right of the page used to report the channel.
Click the flag icon and choose to "Report user".
A JS modal (or whatever) will pop up asking which category you're reporting the channel for.
Within 5 seconds or so that JS modal will close without much time to make a selection.

Let me know if I can provide any more details.

**Comment by own3mall** [comment]
@Ben-Fenner Can you check and see if this version fixes your issues?  Also, can you please let me know if you run into any additional problems from a video's page?  Unfortunately, I can't differentiate the dialogs very well due to YouTube not using any helpful attributes on their continue playback dialog which causes other dialogs using similar code to be dismissed (canceled).   
[YouTubeNonStop_1.0.8.zip](https://github.com/own3mall/YouTubeNonStop-Legacy-XUL-Extension/files/9855251/YouTubeNonStop_1.0.8.zip)

Remove current extension, restart pale moon.  Install the attached and try it.  Let me know.  :)

**Comment by Ben-Fenner** [comment]
Without a channel I know I'd like to report, it is hard to test this 100% but the JS dialog I was talking about certainly remains active very long now. Certainly more than 5 seconds, probably forever (I only checked for ~30 seconds or so).

I would think you've solved this problem. 👍️

I'll let you know if I run into any regressions on YouTube, but if I don't come back in a day or two I'd say this is safe to release. Or release as you wish.

Edit: Yah, YouTube is fine. Ship it.

**Comment by own3mall** [comment]
Awesome, it's been released.  Thanks!
